version: '3'
services:
  beautiful-app:
    build: .
    env_file:
      - .env
    container_name: beautiful-app
    volumes:
      - /app/data/:/some-app/data/
    ports:
      - 8080:8080
    environment:
      - COMPETITOR_ID=${id}

