all:
  vars:
    become: 'yes'
    become_method: 'sudo'
    become_user: "{{ lookup('env','SSH_USERNAME') }}"
    ansible_become_pass: "{{ lookup('env','SSH_PASSWORD') }}"
    ansible_ssh_user: "{{ lookup('env','SSH_USERNAME') }}"
    ansible_ssh_pass: "{{ lookup('env','SSH_PASSWORD') }}"
  hosts:
    node1:
      ansible_ssh_host: "{{ lookup('env','INSTANCE_1') }}"
    # node2:
    #   ansible_ssh_host: "{{ lookup('env','INSTANCE_2') }}"
    # node3:
    #   ansible_ssh_host: "{{ lookup('env','INSTANCE_3') }}"
