all:
  vars:
    become: 'yes'
    become_user: "{{ lookup( 'env','SSH_USERNAME' ) }}"
    ansible_become_pass: "{{ lookup( 'env','SSH_PASSWORD' ) }}"
    become_method: 'sudo' 
    ansible_ssh_user: "{{ lookup( 'env','SSH_USERNAME' ) }}" 
    ansible_ssh_pass: "{{ lookup( 'env','SSH_PASSWORD' ) }}" 
  hosts:
    region1:
      ansible_ssh_host: "{{ lookup( 'env','INSTANCE_1' ) }}"
    region2:
      ansible_ssh_host: "{{ lookup( 'env','INSTANCE_2' ) }}"
    region3:
      ansible_ssh_host: "{{ lookup( 'env','INSTANCE_3' ) }}"