- hosts: 'node2'
  gather_facts: 'no'
  become: 'yes'
  tasks:
    - name: "Copy cert to node2"
      copy: src=../nginx/node2/{{ item }} dest=/etc/nginx/private/
      with_items:
      - app.crt 
      - app.key
    - name: "Restart nginx"
      systemd:
        state: restarted
        daemon_reload: yes
        name: nginx

    - name: "Add peers glusterfs"
      shell: "gluster peer probe {{ lookup('env','INSTANCE_1') }} && gluster peer probe {{ lookup('env','INSTANCE_3') }}"