- hosts: 'node3'
  gather_facts: 'no'
  become: 'yes'
  tasks:
    - name: "Copy cert to node3"
      copy: src=../nginx/node3/{{ item }} dest=/etc/nginx/private/
      with_items:
      - app.crt 
      - app.key
    - name: "Restart nginx"
      systemd:
        state: restarted
        daemon_reload: yes
        name: nginx